### ISSUE TITLE
Really slow to load versions

### ISSUE THREAD

**Issue by dylanvdmerwe** [vscode-contrib/vscode-versionlens#184] opened 2020-04-15 21:16 UTC
Noticed in the last 2 weeks, when opening a packages.json file, the "analyzing dependencies" loading indicator spins for easily in excess of  5-10 minutes before any versions are loaded. Our packages files are not large, and it does this every time the package.json file is opened. 

Has something changed?

![image](https://user-images.githubusercontent.com/2852839/79389798-f4e50000-7f6e-11ea-98e6-2931bba08db0.png)

Version Lens 0.25.0
VS Code 1.44.1
Windows 10

**Comment by pflannery** [comment] 2020-05-03 19:10
@dylanvdmerwe looks like a duplicate of #131 

Can u provide a package.json I can test with? also if this happens again can you open the vscode dev tools and check if there are any errors in the console. thanks

**Comment by dylanvdmerwe** [comment] 2020-05-03 20:17
Waited for over 10 minutes - nothing in dev console and no versions loaded.

My package.json:
```
{
  "name": "wunderlust-app",
  "version": "1.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "stats": "ng build --prod --stats-json && webpack-bundle-analyzer dist/stats-es2015.json",
    "prod": "ng build --prod",
    "nswag": "nswag run ..\\..\\..\\WebServiceProjects\\WebService.SiteApi\\nswag.json /runtime:NetCore30",
    "prebuild": "node environments/prebuild.ts",
    "preprod": "node environments/prebuild.ts"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~9.1.3",
    "@angular/common": "~9.1.3",
    "@angular/compiler": "~9.1.3",
    "@angular/core": "~9.1.3",
    "@angular/fire": "^5.2.3",
    "@angular/forms": "~9.1.3",
    "@angular/platform-browser": "~9.1.3",
    "@angular/platform-browser-dynamic": "~9.1.3",
    "@angular/router": "~9.1.3",
    "@angular/service-worker": "~9.1.3",
    "@auth0/angular-jwt": "^3.0.1",
    "angularx-flatpickr": "^6.3.1",
    "file-saver": "2.0.2",
    "firebase": "^6.4.2",
    "flatpickr": "^4.6.3",
    "https": "^1.0.0",
    "moment": "2.24.0",
    "ng-zorro-antd": "^9.1.0",
    "rxjs": "~6.5.3",
    "tslib": "^1.10.0",
    "web-animations-js": "^2.3.2",
    "web-social-share": "^6.4.0",
    "zone.js": "~0.10.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.3",
    "@angular/cli": "~9.1.3",
    "@angular/compiler-cli": "~9.1.3",
    "@angular/language-service": "~9.1.3",
    "@types/file-saver": "^1.3.1",
    "@types/node": "^12.11.1",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.8.3",
    "webpack-bundle-analyzer": "^3.7.0",
    "build-number-generator": "0.0.6",
    "fs-extra": "8.1.0"
  }
}
```

**Comment by pflannery** [comment] 2020-05-04 11:41
@dylanvdmerwe I'm not seeing any slowness with the example you posted. 
This extension uses the npm view api. Could you try clearing your npm cache? `npm cache clean --force` see how that goes

**Comment by dylanvdmerwe** [comment] 2020-05-04 11:44
@pflannery clearning npm cache did the trick - versions load almost instantly. Bizarre, but thank you! I wonder what the issue was.

**Comment by pflannery** [comment] 2020-05-06 04:24
@dylanvdmerwe The npm performance should be better v0.26.2, let me know how it goes.

**Comment by icleolion** [comment] 2020-05-06 07:38
Just wanted to confirm that 0.26.2 has fixed the error in dev tools and VersionLens is working correctly.  Thank you!

I personally have no issues with performance. It's only a few seconds to load, assuming I'd given VS Code chance to initialise all extensions.

**Closed** 2020-05-06 16:02 UTC
Labels: bug
