### ISSUE TITLE
Extension does not work correctly with 4 number versions of Nuget packages

### ISSUE THREAD

**Issue by DamirAinullin** [vscode-contrib/vscode-versionlens#146] opened 2019-05-29 16:39 UTC
[Here is the example](http://joxi.ru/brR8Y4eI7JDwz2).
At the moment the latest version of AWSSDK.CloudWatch Nuget package is 3.3.101.21.
But the extension suggests 3.3.101. This is wrong. The same thing with other 4 number versions of Nuget packages.

**Comment by psaxton** [comment] 2019-06-21 19:54
This was reported before in #105 and was closed as working as designed.

**Comment by pflannery** [comment] 2019-06-27 23:40
Yes duplicate of #105. 
@DamirAinullin This extension only supports semantic versioning. Closing this.

**Closed by pflannery** 2019-06-27 23:40 UTC
