### ISSUE TITLE
Support private npm registry

### ISSUE THREAD

**Issue by vharadkou** [vscode-contrib/vscode-versionlens#101] opened 2018-04-14 07:52 UTC
Example: 
in .npmrc have some link to repo
@my-private-npm-repo:registry=https://someserver/_packaging/MyComponents/npm/registry/ 

Currently we have something like that:
![image](https://user-images.githubusercontent.com/5987672/38765849-ec2a9c74-3fd1-11e8-98c8-85045d4ff6f4.png)

**Comment by pflannery** [comment] 2018-04-15 01:08
This is a duplicate of #85 and essentially then same as #38

**Closed by pflannery** 2018-04-15 01:08 UTC
