### ISSUE TITLE
Activating extension 'pflannery.vscode-versionlens' failed: Cannot find module 'systemjs'.

### ISSUE THREAD

**Issue by leolcao** [vscode-contrib/vscode-versionlens#97] opened 2018-03-13 14:09 UTC
After upgrade VScode to 1.21.0, versionlens cann't working now, toggle developer tools to get this error message

**Comment by pflannery** [comment] 2018-03-25 13:14
duplicate of https://github.com/vscode-contrib/vscode-versionlens/issues/91#issuecomment-360301349

**Closed by pflannery** 2018-03-25 13:14 UTC
