### ISSUE TITLE
not installing

### ISSUE THREAD

**Issue by SteveALee** [vscode-contrib/vscode-versionlens#237] opened 2020-05-26 13:33 UTC
It's stuck in an install loop between "intalling" and "update to version 1.0.4"

I tried installing from the command line but still get the loop when I enter code.

I have the latest code. tried rebooting etc.

**Comment by LeanderD** [comment] 2020-05-26 13:40
Same here!

**Comment by LeanderD** [comment] 2020-05-26 13:44
Fixed it by installing it manually:
`code --install-extension vscode-versionlens-1.0.4.vsix`

See releases page: [Versionlens Releases](https://github.com/vscode-contrib/vscode-versionlens/releases)

**Comment by jamesmosier** [comment] 2020-05-26 13:57
Looks to be a duplicate of https://github.com/vscode-contrib/vscode-versionlens/issues/211

**Comment by pflannery** [comment] 2020-05-26 14:35
> Looks to be a duplicate of #211

**Closed by pflannery** 2020-05-26 14:35 UTC
