### ISSUE TITLE
"Installing" loop after upgrade to 1.0.0

### ISSUE THREAD

**Issue by FedericoBiccheddu** [vscode-contrib/vscode-versionlens#213] opened 2020-05-22 10:14 UTC
After installing the `1.0.0`, VSCode keeps telling me to update the extension to `1.0.1`.

When I click `Update to 1.0.1` the extension enter in a loop between "Installing" and "Update to 1.0.1".

VSCode:
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:22.494Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-53-generic
```

PS: thank you for the extension and your work.

**Comment by webcoderkz** [comment] 2020-05-22 10:23
I've got the same issue.

**Comment by pflannery** [comment] 2020-05-22 10:34
duplicate of #211

**Closed by pflannery** 2020-05-22 10:34 UTC
